---
title: "LAB_008"
author: "Mike James"
date: "3/4/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

***
### Chapter 4 or 5 from some book we have

***

```{r}
# summary(LeafData)
install.packages("Rmisc")
library(Rmisc)
summarySE(data = LeafData, measurevar = 'LEAF.L', groupvars = c('PARK','LIFE.STAGE'))
boxplot(data = LeafData, HEIGHT~PARK)
# install.packages("gplots")
# install.packages("ggplot2")
library(gplots)
library(ggplot2)

# This makes use of gplot
plotmeans(data = LeafData, HEIGHT~PARK)

# Again, the line connecting the two is useless garbage
boxplot(data = LeafData, HEIGHT~PARK*LIFE.STAGE)

# This uses ggplot2
ggplot(aes(HEIGHT, PARK), data = LeafData, c('HEIGHT','PARK*LIFE.STAGES')) + geom_point()
```

***

### Two-Way ANOVA

```{r}
install.packages("ISwR")
library(ISwR)
data(coking)
attach(coking)
head(coking)
anova(lm(time~width*temp))

# df of width:temp is width*temp (i.e. 2*1)
# F is MS / residuals ONLY IF THE TREATMENTS ARE FIXED EFFECTS

# Moving on to AOV

anova(aov(time~width*temp))
summary(aov(time~width*temp))
detach(coking)
```

***

```{r}
data(CO2)
attach(CO2)
summary(CO2)
co2.2way <- aov(uptake~Type*Treatment)
summary(co2.2way)
plot(co2.2way)

# Something in the Quebec plants is interacting with the treatments

TukeyHSD(co2.2way)

# 3-way ANOVA

co2.conc <- as.factor(CO2$conc)
levels(co2.conc)
co2.3way <- aov(uptake~Type*Treatment*co2.conc)
summary(co2.3way)
detach(CO2)
```

***

### Model III ANOVA

```{r}
# install.packages("lme4")
library(lme4)
LeafData[1:5,]
leaf.lmer <- lmer(data = LeafData, HEIGHT~LIFE.STAGE*PARK + (1|PARK))
anova(leaf.lmer)

# (1|PARK) = 

```
